In [2]:
# 1. Download data.zip from the celebrity faces dataset from kaggle at 
# https://www.kaggle.com/dansbecker/5-celebrity-faces-dataset/data

# Important OpenCV face detection and classification links
# https://realpython.com/blog/python/face-recognition-with-python/
# https://www.superdatascience.com/opencv-face-detection/
# https://www.superdatascience.com/opencv-face-recognition/

In [2]:
#Load all necessary libraries
import numpy as np
import cv2 # opencv
import os # control and access the directory structure in local machine
from matplotlib import pyplot as plt
import time


In [3]:
os.chdir('C:/Users/rithanya/Documents/Python/faces/') #folder where I unzipped data.zip

#OpenCV cascades (xml files) are typically stored at this location
#C:\Users\<user>\Miniconda3\Library\etc\haarcascades
haarcascades_path = os.listdir('C:/Users/rithanya/Miniconda3/Library/etc/haarcascades/')
frontface_alt_cascade = 'C:/Users/rithanya/Miniconda3/Library/etc/haarcascades/haarcascade_frontalface_alt.xml'
frontface_default_cascade = 'C:/Users/rithanya/Miniconda3/Library/etc/haarcascades/haarcascade_frontalface_default.xml'
frontface_alt2_cascade = 'C:/Users/rithanya/Miniconda3/Library/etc/haarcascades/haarcascade_frontalface_alt2.xml'
frontface_alt_tree_cascade = 'C:/Users/rithanya/Miniconda3/Library/etc/haarcascades/haarcascade_frontalface_alt2.xml'

lbpcascadesPath = os.listdir("C:/Users/rithanya/Miniconda3/Library/etc/lbpcascades/")

lbp_frontface_path = "C:/Users/rithanya/Miniconda3/Library/etc/lbpcascades/lbpcascade_frontalface.xml"
lbp_fronface_improved_path = "C:/Users/rithanya/Miniconda3/Library/etc/lbpcascades/lbpcascade_frontalface_improved.xml"
lbp_frontface_profile_path = "C:/Users/rithanya/Miniconda3/Library/etc/lbpcascades/lbpcascade_profileface.xml"

In [4]:
#utility function to apply differenct cascade function on the images at difference scaleFactor
def detect(faceCascade, gray_,  scaleFactor_ = 1.1):
    faces = faceCascade.detectMultiScale(
                    gray_,
                    scaleFactor= scaleFactor_,
                    minNeighbors=5,
                    minSize=(30, 30),
                    flags = cv2.CASCADE_SCALE_IMAGE
                )
    return faces

In [40]:
# Code to test the detection accurace of Haar cascades
faceCascade_default = cv2.CascadeClassifier(frontface_default_cascade)
faceCascade_alt = cv2.CascadeClassifier(frontface_alt_cascade)
faceCascade_alt2 = cv2.CascadeClassifier(frontface_alt2_cascade)
faceCascade_alt_tree = cv2.CascadeClassifier(frontface_alt_tree_cascade)
i = 0
t1 = time.time()
for imgfolder in os.listdir('train/'): #iterate thru each of the 5 celeb folders
    if(imgfolder != '.DS_Store'):
        for filename in os.listdir('train/' + imgfolder):# iterate thru each image in a celeb folder
            filename = 'train/' + imgfolder + '/' + filename # build the path to the image file
            if(filename.endswith('.jpg')):
                #print(filename) # print the filename read. For debugging purpose only
                img = cv2.imread(filename) # read the image using OpenCV
                gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
                faces = detect(faceCascade_default, gray, 1.1)
                if (len(faces)!=1):
                    faces = detect(faceCascade_default, gray, 1.2)
                    if(len(faces) != 1):
                        faces = detect(faceCascade_alt2,gray, 1.1)
                        if(len(faces) != 1):
                            faces = detect(faceCascade_alt2,gray, 1.2)
                            if(len(faces) != 1):
                                faces = detect(faceCascade_alt, gray, 1.1)
                                if(len(faces) != 1):
                                    faces = detect(faceCascade_alt, gray, 1.2)
                                    if(len(faces) != 1):
                                        faces = detect(faceCascade_alt_tree, gray, 1.1)
                                        if(len(faces) != 1):
                                            faces = detect(faceCascade_alt_tree, gray, 1.2)
                                            if(len(faces) != 1):
                                                i = i + 1
                                                continue
                                                for (x, y, w, h) in faces:
                                                    cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)
                                                plt.imshow(img, cmap = 'gray', interpolation = 'bicubic') # display all images read
                                                print(filename) # print the filename read. For debugging purpose only
                                                plt.xticks([]), plt.yticks([])
                                                plt.show()
                                                

t2 = time.time()
print ('Time taken %f seconds' %  round((t2 - t1),2))
print(i)

Time taken 3.510000 seconds
9


In [5]:
# code that iterates thru the images in the celebrityfaces dataset and detects faces. Finally it
# ... only displays those images that it can't detect the faces.
lbp_frontfaceCascade = cv2.CascadeClassifier(lbp_frontface_path)
lbp_fronfaceimprovedCascade = cv2.CascadeClassifier(lbp_fronface_improved_path)
lbp_profileCascade = cv2.CascadeClassifier(lbp_frontface_profile_path)



In [38]:
# Code to test the detection accurace of lbp cascades
i = 0
t1 = time.time()

for imgfolder in os.listdir('train/'): #iterate thru each of the 5 celeb folders
    if(imgfolder != '.DS_Store'):
        for filename in os.listdir('train/' + imgfolder):# iterate thru each image in a celeb folder
            filename = 'train/' + imgfolder + '/' + filename # build the path to the image file
            if(filename.endswith('.jpg')):
                #print(filename) # print the filename read. For debugging purpose only
                img = cv2.imread(filename) # read the image using OpenCV
                gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
                faces = detect(lbp_frontfaceCascade, gray, 1.1)
                if(len(faces) != 1):
                    faces = detect(lbp_frontfaceCascade, gray, 1.2)
                    if(len(faces) != 1):
                        faces = detect(lbp_fronfaceimprovedCascade, gray, 1.1)
                        if(len(faces) != 1):
                            faces = detect(lbp_fronfaceimprovedCascade, gray, 1.2)
                            if(len(faces) != 1):
                                faces = detect(lbp_profileCascade, gray, 1.1)
                                if(len(faces) != 1):
                                    faces = detect(lbp_profileCascade, gray, 1.2)
                                    if(len(faces) != 1):
                                        i = i +1
                                        continue
                                        for (x, y, w, h) in faces:
                                            cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)
                                        plt.imshow(img, cmap = 'gray', interpolation = 'bicubic') # display all images read
                                        print(filename) # print the filename read. For debugging purpose only
                                        plt.xticks([]), plt.yticks([])
                                        plt.show()
                    
t2 = time.time()
print ('Time taken %f seconds' %  np.round((t2 - t1),2))
print(i)

Time taken 1.460000 seconds
16


In [6]:
#function to detect face using OpenCV
def detect_face(img, face_cascade):
    #convert the test image to gray scale as opencv face detector expects gray images
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    #load OpenCV face detector, I am using LBP which is fast
    #there is also a more accurate but slow: Haar classifier
    #face_cascade = cv2.CascadeClassifier('opencv-files/lbpcascade_frontalface.xml')

    #let's detect multiscale images(some images may be closer to camera than others)
    #result is a list of faces
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5);

    #if no faces are detected then return original img
    if (len(faces) == 0):
        return None, None

    #under the assumption that there will be only one face,
    #extract the face area
    (x, y, w, h) = faces[0]

    #return only the face part of the image
    return gray[y:y+w, x:x+h], faces[0]

In [7]:
#this function will read all persons' training images, detect face from each image
#and will return two lists of exactly same size, one list 
#of faces and another list of labels for each face
def prepare_training_data(trainfolder = 'train/'):
    
    #list to hold all subject faces
    faces = []
    #list to hold labels for all subjects
    labels = []
    label_names = ['']
    #lbp_frontfaceCascade = cv2.CascadeClassifier(lbp_frontface_path)
    haar_faceCascade_default = cv2.CascadeClassifier(frontface_default_cascade)
    detected_images = []
    for imgfolder in os.listdir(trainfolder): #iterate thru each of the 5 celeb folders
        if(imgfolder != '.DS_Store'):
            label_names.append(imgfolder)
            for filename in os.listdir(trainfolder + imgfolder):# iterate thru each image in a celeb folder
                filename = trainfolder + imgfolder + '/' + filename # build the path to the image file
                if(filename.endswith('.jpg')):
                    img = cv2.imread(filename) # read the image using OpenCV
                    #detect face
                    face, rect = detect_face(img, haar_faceCascade_default) # lbp_frontfaceCascade)

                    #------STEP-4--------
                    #for the purpose of this tutorial
                    #we will ignore faces that are not detected
                    if face is not None:
                        #add face to list of faces
                        faces.append(face)
                        #add label for this face
                        labels.append(label_names.index(imgfolder))
                        detected_images.append(filename)
                        continue
                        plt.imshow(face, cmap = 'gray', interpolation = 'bicubic') # display all images read
                        plt.xticks([]), plt.yticks([])
                        plt.show()

                        

    return faces, labels, detected_images, label_names

In [8]:
#let's first prepare our training data
#data will be in two lists of same size
#one list will contain all the faces
#and the other list will contain respective labels for each face
print("Preparing data...")
#instatiate haar has 5 cascades, lbp
faces, labels, detectedimages, label_names = prepare_training_data('rotate/')
print("Data prepared")

#print total faces and labels
print("Total faces: ", len(faces))
print("Total labels: ", len(labels))
print(detectedimages[0])
#print(labels)

Preparing data...
Data prepared
Total faces:  150
Total labels:  150
rotate/ben_afflek/httpcsvkmeuaeccjpg_rotate.jpg


In [11]:
#create our LBPH face recognizer 
face_recognizer = cv2.face.LBPHFaceRecognizer_create()


#or use EigenFaceRecognizer by replacing above line with 
#face_recognizer = cv2.face.createEigenFaceRecognizer()

#or use FisherFaceRecognizer by replacing above line with 
#face_recognizer = cv2.face.createFisherFaceRecognizer()

In [13]:
#train our face recognizer of our training faces
#face_recognizer.train(faces, np.array(labels))
face_recognizer.train(Xtrain, np.array(ytrain))

In [14]:
#function to draw rectangle on image 
#according to given (x, y) coordinates and 
#given width and heigh
def draw_rectangle(img, rect):
    (x, y, w, h) = rect
    cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)
 
#function to draw text on give image starting from
#passed (x, y) coordinates. 
def draw_text(img, text, x, y):
     cv2.putText(img, text, (x, y), cv2.FONT_HERSHEY_PLAIN, 1.5, (0, 255, 0), 2)

In [19]:
#Code to perform prediction on the Test dataset image
def predict_train(face):
    #make a copy of the image as we don't want to change original image
    #img = test_img.copy()
    #detect face from the image
    #face, rect = detect_face(img, faceCascade_default) #lbp_frontfaceCascade)
    #if(face is not None):
        #predict the image using our face recognizer 
    label= face_recognizer.predict(face)
        #get name of respective label returned by face recognizer
        #print(label[0])
    label_text = label_names[label[0]]

        #draw a rectangle around face detected
        #draw_rectangle(img, rect)
        #draw name of predicted person
        #draw_text(img, label_text, rect[0], rect[1]-5)

    return face, label_text
    #else:
    #    return None, None

In [9]:
#Code to perform cross validation to get Training Score...
def cross_val(cv = 5):
    scores = []
    while(cv > 0):
        cv = cv - 1
        from sklearn.cross_validation import train_test_split
        Xtrain, Xtest, ytrain, ytest = train_test_split(faces, labels)

        #print(len(Xtrain))
        #print(len(Xtest))
        #print(ytrain)
        #print(ytest)
        face_recognizer = cv2.face.LBPHFaceRecognizer_create()
        face_recognizer.train(Xtrain, np.array(ytrain))
        test_labels = []
        pred_labels = []
        i = -1
        for face in Xtest:
            i = i + 1
            label = face_recognizer.predict(face)
            label_text = label_names[label[0]]
            #face, label = predict_train(face)
            #print(label_names)
            #print(ytest[i])
            test_labels.append(label_names[ytest[i]])
            pred_labels.append(label_text)

        from sklearn.metrics import accuracy_score
        scores.append(accuracy_score(test_labels, pred_labels))
    return scores

        #from sklearn.metrics import confusion_matrix
        #print(confusion_matrix(test_labels, pred_labels))


In [10]:
print('Cross Validation to get Training Score...')
scores =  cross_val(20)
print (scores)
print(np.mean(scores))


Cross Validation to get Training Score...


C:\Users\rithanya\Miniconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


[0.55263157894736847, 0.71052631578947367, 0.78947368421052633, 0.76315789473684215, 0.76315789473684215, 0.81578947368421051, 0.76315789473684215, 0.68421052631578949, 0.60526315789473684, 0.65789473684210531, 0.65789473684210531, 0.65789473684210531, 0.65789473684210531, 0.60526315789473684, 0.73684210526315785, 0.73684210526315785, 0.60526315789473684, 0.76315789473684215, 0.78947368421052633, 0.71052631578947367]
0.701315789474


In [43]:
#Code to perform prediction on the Validation dataset image
def predict_val(test_img):
    #make a copy of the image as we don't want to change original image
    img = test_img.copy()
    #detect face from the image
    haar_faceCascade_default = cv2.CascadeClassifier(frontface_default_cascade)
    face, rect = detect_face(test_img, haar_faceCascade_default) #lbp_frontfaceCascade)
    face_recognizer = cv2.face.LBPHFaceRecognizer_create()
    face_recognizer.train(faces, np.array(labels))
    if(face is not None):
        #predict the image using our face recognizer 
        label= face_recognizer.predict(face)
        #get name of respective label returned by face recognizer
        #print(label[0])
        label_text = label_names[label[0]]

        #draw a rectangle around face detected
        draw_rectangle(img, rect)
        #draw name of predicted person
        draw_text(img, label_text, rect[0], rect[1]-5)

        return face, label_text, img
    else:
        return None, None, None

In [55]:
#code to perform validation on the model and print validation scores
print("Predicting images...")
test_labels = []
pred_labels = []
for imgfolder in os.listdir('val/'): #iterate thru each of the 5 celeb folders
    for filename in os.listdir('val/' + imgfolder):# iterate thru each image in a celeb folder
        if(filename.endswith('.jpg')):
            file_ = 'val/' + imgfolder + '/' + filename # build the path to the image file
            #for file_ in detectedimages:
            #perform a prediction
            img = cv2.imread(file_)
            pred_face, pred_label, pred_img = predict_val(img)
            if(pred_face is not None):
                test_labels.append(imgfolder)
                pred_labels.append(pred_label)
                continue
                plt.imshow(pred_img, cmap = 'gray', interpolation = 'bicubic') # display all images read
                plt.xticks([]), plt.yticks([])
                plt.show()
            else:
                print("Prediction failed for %s" %file_)
                
                
print("Validation Scores..")
from sklearn.metrics import accuracy_score
print(accuracy_score(test_labels, pred_labels))
    
from sklearn.metrics import confusion_matrix
print(confusion_matrix(test_labels, pred_labels))



Predicting images...
Validation Scores..
0.56
[[3 0 2 0 0]
 [0 2 2 1 0]
 [0 1 3 1 0]
 [1 1 1 2 0]
 [0 0 0 1 4]]
